### ISSUE TITLE
[ESP32] Upgrading Xtensa toolchain to 1.22.0-98

### ISSUE THREAD

**Issue by amotl** [BradenM/micropy-build#6]
Dear Braden,

thanks for conceiving such excellent tools for supporting MicroPython development. 

At https://github.com/BradenM/micropy-build/blob/e912da7f7f4a6c9fb9abb5077ef6d226530206f1/esp32/Dockerfile#L53 I am seeing the pipeline will still acquire the Xtensa toolchain version 1.22.0-80. However, we learned from https://github.com/espressif/esp-idf/issues/2892 that toolchain version 1.22.0-98 works around some critical silicon bugs, so you might consider upgrading as well.

With kind regards,
Andreas.

**Comment by BradenM** [comment]
Sure!

Thanks for the heads up.

**Comment by amotl** [comment]
That was quick. Thanks!
